# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='fr', max_length=10)),
                ('country', models.CharField(default='France', max_length=50)),
                ('active_re2020', models.BooleanField(default=True)),
                ('active_rt2012', models.BooleanField(default=True)),
                ('active_rt2012_re2020', models.BooleanField(default=False)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('currency_symbol', models.CharField(default='€', max_length=5)),
                ('vat_rate', models.FloatField(default=20.0)),
                ('company_name', models.CharField(blank=True, default='ThermConform', max_length=255)),
                ('company_phone', models.CharField(blank=True, default='01 23 45 67 89', max_length=50)),
                ('company_address', models.CharField(blank=True, default='Paris, France', max_length=255)),
                ('email_sender', models.EmailField(blank=True, default='contact@thermconform.fr', max_length=254)),
                ('email_footer', models.TextField(blank=True, default="ThermConform — Bureau d'études thermiques certifié. Ne pas répondre à cet email.")),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
