# Generated by Django 5.0.6 on 2024-07-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_document_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='carbon_emissions',
        ),
        migrations.RemoveField(
            model_name='document',
            name='energy_efficiency',
        ),
        migrations.RemoveField(
            model_name='document',
            name='indoor_air_quality',
        ),
        migrations.RemoveField(
            model_name='document',
            name='thermal_comfort',
        ),
        migrations.RemoveField(
            model_name='document',
            name='water_management',
        ),
        migrations.AddField(
            model_name='document',
            name='re2020_carbon_emissions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='re2020_energy_efficiency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='re2020_indoor_air_quality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='re2020_thermal_comfort',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='re2020_water_management',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='rt2012_carbon_emissions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='rt2012_energy_efficiency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='rt2012_indoor_air_quality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='rt2012_thermal_comfort',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='document',
            name='rt2012_water_management',
            field=models.FloatField(default=0.0),
        ),
    ]
