# Generated by Django 5.0.6 on 2024-07-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_document_carbon_emissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='re2020_carbon_emissions',
            field=models.FloatField(default=75.0),
        ),
        migrations.AlterField(
            model_name='document',
            name='re2020_energy_efficiency',
            field=models.FloatField(default=80.0),
        ),
        migrations.AlterField(
            model_name='document',
            name='re2020_indoor_air_quality',
            field=models.FloatField(default=75.0),
        ),
        migrations.AlterField(
            model_name='document',
            name='re2020_thermal_comfort',
            field=models.FloatField(default=85.0),
        ),
        migrations.AlterField(
            model_name='document',
            name='re2020_water_management',
            field=models.FloatField(default=70.0),
        ),
        migrations.AlterField(
            model_name='document',
            name='rt2012_carbon_emissions',
            field=models.FloatField(default=35.0),
        ),
        migrations.AlterField(
            model_name='document',
            name='rt2012_energy_efficiency',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='document',
            name='rt2012_indoor_air_quality',
            field=models.FloatField(default=800.0),
        ),
        migrations.AlterField(
            model_name='document',
            name='rt2012_thermal_comfort',
            field=models.FloatField(default=22.0),
        ),
        migrations.AlterField(
            model_name='document',
            name='rt2012_water_management',
            field=models.FloatField(default=120.0),
        ),
    ]
