# Generated by Django 5.0.6 on 2024-07-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_document_re2020_carbon_emissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('energy_efficiency', models.FloatField()),
                ('thermal_comfort', models.FloatField()),
                ('carbon_emissions', models.FloatField()),
                ('water_management', models.FloatField()),
                ('indoor_air_quality', models.FloatField()),
            ],
        ),
    ]
